a,b,c=map(int,input('enter a, b & c :').split(' '))
d = (b**2) - (4*a*c)
sol1 = (-b-(d**0.5))/(2*a)
sol2 = (-b+(d**0.5))/(2*a)
print('solutions are')
print('sol1 = ',sol1)
print('sol2 = ',sol2)
